import { db, Place, Event, TemplateTour } from './database';

const attractions: Place[] = [
  {
    id: '1',
    name: 'Senso-ji Temple',
    category: 'Temple',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 9802,
    ward: 'Asakusa',
    address: '2 Chome-3-1 Asakusa, Taito',
    coordinates: { lat: 35.7148, lng: 139.7967 },
    images: ['https://github.com/imnotkeril/images/blob/main/sensoji.png?raw=true'],
    description: "Senso-ji is Tokyo's oldest temple, founded in 628 AD. This ancient Buddhist temple is dedicated to Kannon, the Goddess of Mercy. The temple's magnificent architecture and rich history make it one of Tokyo's most visited sites.",
    openingHours: '6:00 AM - 5:00 PM',
    admissionFee: 0,
    avgVisitDuration: 90,
    nearestStation: 'Asakusa Station (3 min walk)',
    features: ['English support', 'Wheelchair accessible'],
  },
  {
    id: '2',
    name: 'Tokyo Skytree',
    category: 'Observation Deck',
    type: 'attraction',
    rating: 4.2,
    reviewCount: 8532,
    ward: 'Sumida',
    address: '1 Chome-1-2 Oshiage, Sumida',
    coordinates: { lat: 35.7101, lng: 139.8107 },
    images: ['https://github.com/imnotkeril/images/blob/main/6a90c22292600a24d61914a661465d49.jpg?raw=true'],
    description: 'Standing at 634 meters, Tokyo Skytree is the tallest structure in Japan. The observation decks offer breathtaking 360-degree views of Tokyo and beyond, including Mount Fuji on clear days.',
    openingHours: '9:00 AM - 10:00 PM',
    admissionFee: 2100,
    avgVisitDuration: 120,
    nearestStation: 'Tokyo Skytree Station (2 min walk)',
    features: ['English support', 'Wheelchair accessible'],
  },
  {
    id: '3',
    name: 'Meiji Shrine',
    category: 'Shrine',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 8460,
    ward: 'Shibuya',
    address: '1-1 Yoyogikamizonocho, Shibuya',
    coordinates: { lat: 35.6764, lng: 139.6993 },
    images: ['https://github.com/imnotkeril/images/blob/main/0c23f530fbf99f1304fffa14f408e19b.jpg?raw=true'],
    description: 'Meiji Shrine is a Shinto shrine dedicated to Emperor Meiji and Empress Shoken. Located in a serene forest in the heart of Tokyo, it offers a peaceful retreat from the bustling city.',
    openingHours: 'Sunrise - Sunset',
    admissionFee: 0,
    avgVisitDuration: 75,
    nearestStation: 'Harajuku Station (5 min walk)',
    features: ['English support', 'Wheelchair accessible'],
  },
  {
    id: '4',
    name: 'Shibuya Crossing',
    category: 'Modern Architecture',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 7850,
    ward: 'Shibuya',
    address: '2 Chome-2-1 Dogenzaka, Shibuya',
    coordinates: { lat: 35.6595, lng: 139.7004 },
    images: ['https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=center,quality=60,width=400,height=265,dpr=2/tour_img/5e9208230b30188b8de9cdd1bbb10f204c0b6ee73bf256d5178428a572b7e59d.jpeg'],
    description: "Known as the world's busiest pedestrian crossing, Shibuya Crossing is an iconic Tokyo landmark. Watch up to 3,000 people cross at once from the Starbucks overlooking the intersection.",
    openingHours: '24/7',
    admissionFee: 0,
    avgVisitDuration: 30,
    nearestStation: 'Shibuya Station (1 min walk)',
    features: ['Open 24/7'],
  },
  {
    id: '5',
    name: 'Tokyo Tower',
    category: 'Observation Deck',
    type: 'attraction',
    rating: 4.2,
    reviewCount: 8506,
    ward: 'Minato',
    address: '4 Chome-2-8 Shibakoen, Minato',
    coordinates: { lat: 35.6586, lng: 139.7454 },
    images: ['https://github.com/imnotkeril/images/blob/main/47a9f120124a8025f7bb65e3c2239400-TokyoTowerNightView.jpg?raw=true'],
    description: 'Inspired by the Eiffel Tower, Tokyo Tower has been an iconic symbol of Tokyo since 1958. The observation decks offer stunning city views, especially beautiful at night.',
    openingHours: '9:00 AM - 11:00 PM',
    admissionFee: 1200,
    avgVisitDuration: 90,
    nearestStation: 'Kamiyacho Station (7 min walk)',
    features: ['English support', 'Wheelchair accessible'],
  },
  {
    id: '6',
    name: 'Imperial Palace',
    category: 'Historic Site',
    type: 'attraction',
    rating: 3.8,
    reviewCount: 2905,
    ward: 'Chiyoda',
    address: '1-1 Chiyoda, Chiyoda',
    coordinates: { lat: 35.6852, lng: 139.7528 },
    images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/fe/c7/b8/caption.jpg?w=1200&h=-1&s=1'],
    description: "The Imperial Palace is the primary residence of the Emperor of Japan. The beautiful East Gardens are open to the public and feature traditional Japanese gardens.",
    openingHours: '9:00 AM - 4:30 PM',
    admissionFee: 0,
    avgVisitDuration: 120,
    nearestStation: 'Tokyo Station (10 min walk)',
    features: ['English support'],
  },
  {
    id: '7',
    name: 'Ueno Park',
    category: 'Park',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 5387,
    ward: 'Ueno',
    address: '5-20 Uenokoen, Taito',
    coordinates: { lat: 35.7148, lng: 139.7744 },
    images: ['https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=center,quality=60,width=400,height=265,dpr=2/tour_img/879711ec4d3ef330b41126b22c81db42566d06448fd402b6d730a9e85c915e4a.jpg'],
    description: 'Ueno Park is a spacious public park featuring museums, a zoo, and beautiful cherry blossoms in spring. A perfect spot for a leisurely day outdoors.',
    openingHours: '5:00 AM - 11:00 PM',
    admissionFee: 0,
    avgVisitDuration: 180,
    nearestStation: 'Ueno Station (5 min walk)',
    features: ['English support', 'Wheelchair accessible'],
  },
  {
    id: '8',
    name: 'Akihabara',
    category: 'Shopping District',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 7850,
    ward: 'Akihabara',
    address: 'Sotokanda, Chiyoda',
    coordinates: { lat: 35.7022, lng: 139.7744 },
    images: ['https://i0.wp.com/thecreativeadventurer.com/wp-content/uploads/2020/01/Your-Essential-Guide-To-Exploring-The-Otaku-Neighborhood-Of-Akihabara-Tokyo_45.jpg?resize=1000%2C750&ssl=1'],
    description: "Tokyo's electric town, famous for electronics, anime, manga, and gaming culture. A paradise for tech enthusiasts and otaku.",
    openingHours: '10:00 AM - 8:00 PM',
    admissionFee: 0,
    avgVisitDuration: 120,
    nearestStation: 'Akihabara Station (1 min walk)',
    features: ['English support'],
  },
  {
    id: '9',
    name: 'Tokyo National Museum',
    category: 'Museum',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 2593,
    ward: 'Ueno',
    address: '13-9 Uenokoen, Taito',
    coordinates: { lat: 35.7188, lng: 139.7764 },
    images: ['https://www.japan-guide.com/g18/3054_tokyo_01.jpg'],
    description: "Japan's oldest and largest museum. Houses the world's largest collection of Japanese art and artifacts spanning thousands of years.",
    openingHours: '9:30 AM - 5:00 PM',
    admissionFee: 1000,
    avgVisitDuration: 150,
    nearestStation: 'Ueno Station (10 min walk)',
    features: ['English support', 'Audio guide available'],
  },
  {
    id: '10',
    name: 'Ryogoku Kokugikan',
    category: 'Sumo Arena',
    type: 'attraction',
    rating: 4.5,
    reviewCount: 908,
    ward: 'Sumida',
    address: '1 Chome-3-28 Yokoami, Sumida',
    coordinates: { lat: 35.6975, lng: 139.7933 },
    images: ['https://en.japantravel.com/photo/poi-28-214280/1200x630/tokyo-ryogoku-kokugikan-214280.jpg'],
    description: 'National sumo arena hosting official tournaments three times a year. Visit the sumo museum even during off-season.',
    openingHours: '10:00 AM - 4:30 PM',
    admissionFee: 2500,
    avgVisitDuration: 180,
    nearestStation: 'Ryogoku Station (1 min walk)',
    features: ['English support', 'Sumo museum'],
  },
  {
    id: '11',
    name: 'Kabukiza Theatre',
    category: 'Theatre',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 1039,
    ward: 'Ginza',
    address: '4 Chome-12-15 Ginza, Chuo',
    coordinates: { lat: 35.6698, lng: 139.7703 },
    images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/2a/00/94/caption.jpg?w=900&h=-1&s=1'],
    description: 'Premier kabuki theater in Tokyo. Experience traditional Japanese performing arts with English audio guides available.',
    openingHours: '11:00 AM - 9:00 PM',
    admissionFee: 4000,
    avgVisitDuration: 180,
    nearestStation: 'Higashi-Ginza Station (1 min walk)',
    features: ['English audio guide', 'Single act tickets available'],
  },
  {
    id: '12',
    name: 'Hamarikyu Gardens',
    category: 'Garden',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 1984,
    ward: 'Chuo',
    address: '1-1 Hamarikyuteien, Chuo',
    coordinates: { lat: 35.6596, lng: 139.7634 },
    images: ['https://www.japan-guide.com/g18/3025_02.jpg'],
    description: 'Traditional Japanese garden with seawater pond, teahouse, and stunning views of Tokyo skyline. Perfect for traditional tea ceremony experience.',
    openingHours: '9:00 AM - 5:00 PM',
    admissionFee: 300,
    avgVisitDuration: 90,
    nearestStation: 'Shiodome Station (7 min walk)',
    features: ['Tea house', 'English support', 'Wheelchair accessible'],
  },
  {
    id: '13',
    name: 'Zozoji Temple',
    category: 'Temple',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 3000,
    ward: 'Minato',
    address: '4 Chome-7-35 Shibakoen, Minato',
    coordinates: { lat: 35.6575, lng: 139.7479 },
    images: ['https://www.japan-guide.com/g18/3010_01.jpg'],
    description: 'Historic Buddhist temple with Tokyo Tower as backdrop. Home to six Tokugawa shoguns, featuring beautiful architecture and peaceful grounds.',
    openingHours: '6:00 AM - 5:30 PM',
    admissionFee: 0,
    avgVisitDuration: 60,
    nearestStation: 'Onarimon Station (3 min walk)',
    features: ['English support', 'Historic site'],
  },
  {
    id: '14',
    name: 'Nakano Broadway',
    category: 'Shopping District',
    type: 'attraction',
    rating: 4.1,
    reviewCount: 534,
    ward: 'Nakano',
    address: '5 Chome-52-15 Nakano, Nakano',
    coordinates: { lat: 35.7059, lng: 139.6647 },
    images: ['https://www.japan-guide.com/g18/3069_01.jpg'],
    description: 'Underground otaku paradise. Four floors packed with manga, anime figures, vintage toys, and collectibles. Less touristy than Akihabara.',
    openingHours: '12:00 PM - 8:00 PM',
    admissionFee: 0,
    avgVisitDuration: 120,
    nearestStation: 'Nakano Station (5 min walk)',
    features: ['Otaku culture', 'Manga shop', 'Anime goods'],
  },
  {
    id: '15',
    name: 'Mandarake Complex',
    category: 'Store',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 6000,
    ward: 'Akihabara',
    address: '3 Chome-11-12 Sotokanda, Chiyoda',
    coordinates: { lat: 35.7022, lng: 139.7708 },
    images: ['https://www.datocms-assets.com/101439/1758001534-mandarake-akihabara-complex.jpg?auto=format&fit=max&w=1200'],
    description: '8 floors of anime, manga, and collectibles. From vintage to latest releases, cosplay items to rare figures.',
    openingHours: '12:00 PM - 8:00 PM',
    admissionFee: 0,
    avgVisitDuration: 90,
    nearestStation: 'Akihabara Station (3 min walk)',
    features: ['Tax-free shopping', 'Multiple floors', 'Rare collectibles'],
  },
  {
    id: '17',
    name: 'teamLab Borderless',
    category: 'Digital Art',
    type: 'attraction',
    rating: 4.5,
    reviewCount: 206,
    ward: 'Azabudai',
    address: '1 Chome-2-4 Azabudai, Minato',
    coordinates: { lat: 35.6601, lng: 139.7432 },
    images: ['https://thirdeyetraveller.com/wp-content/uploads/teamlab-borderless-tokyo-worth-visiting-8-689x551.jpg'],
    description: 'Mind-blowing digital art museum with interactive installations. Immersive experience that changes based on visitor interaction.',
    openingHours: '8:30 AM - 9:00 PM',
    admissionFee: 3800,
    avgVisitDuration: 150,
    nearestStation: 'Azabudai Station (1 min walk)',
    features: ['English support', 'Photography allowed', 'Reservations recommended'],
  },
  {
    id: '18',
    name: 'Mt. Fuji 5th Station',
    category: 'Mountain',
    type: 'attraction',
    rating: 4.2,
    reviewCount: 867,
    ward: 'Fujiyoshida',
    address: 'Mt. Fuji, Fujiyoshida, Yamanashi',
    coordinates: { lat: 35.3606, lng: 138.7274 },
    images: ['https://www.japan-guide.com/g18/6922_01.jpg'],
    description: 'Halfway point on Mt. Fuji accessible by bus. Breathtaking views, gift shops, and starting point for summit hikes.',
    openingHours: '7:00 AM - 5:00 PM',
    admissionFee: 0,
    avgVisitDuration: 120,
    nearestStation: 'Bus from Kawaguchiko Station (50 min)',
    features: ['Scenic views', 'Gift shops', 'Hiking trails'],
  },
  {
    id: '19',
    name: 'Lake Kawaguchiko',
    category: 'Nature',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 2377,
    ward: 'Fujikawaguchiko',
    address: 'Fujikawaguchiko, Minamitsuru District, Yamanashi',
    coordinates: { lat: 35.5089, lng: 138.7640 },
    images: ['https://www.japan-guide.com/g18/6906_01.jpg'],
    description: 'Picturesque lake offering postcard-perfect views of Mt. Fuji. Boat rides, scenic walks, and photography opportunities.',
    openingHours: '24/7',
    admissionFee: 0,
    avgVisitDuration: 180,
    nearestStation: 'Kawaguchiko Station (5 min walk)',
    features: ['Boat tours', 'Scenic views', 'Photography spot'],
  },
  {
    id: '20',
    name: 'Oishi Park',
    category: 'Park',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 800,
    ward: 'Fujikawaguchiko',
    address: '2585-1 Oishi, Fujikawaguchiko',
    coordinates: { lat: 35.5182, lng: 138.7832 },
    images: ['https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=center,quality=60,width=400,height=265,dpr=2/tour_img/7dbdddaa8a3ca4edecd645781f4c4df08e8e5bd2c916248a0620a16012d67b98.jpeg'],
    description: 'Beautiful flower park with stunning Mt. Fuji views. Famous for lavender fields in summer and colorful blooms year-round.',
    openingHours: '9:00 AM - 5:00 PM',
    admissionFee: 0,
    avgVisitDuration: 90,
    nearestStation: 'Bus from Kawaguchiko Station (20 min)',
    features: ['Seasonal flowers', 'Photography spot', 'Cafe'],
  },
  {
    id: '21',
    name: 'National Museum of Nature and Science',
    category: 'Museum',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 1300,
    ward: 'Ueno',
    address: '7-20 Uenokoen, Taito',
    coordinates: { lat: 35.7164, lng: 139.7761 },
    images: ['https://cdn.gaijinpot.com/app/uploads/sites/6/2016/05/National-Musuem-of-Nature-and-Science-Ueno.jpg'],
    description: 'Leading science museum featuring natural history and scientific exhibitions. Famous for the life-size blue whale model and dinosaur fossils.',
    openingHours: '9:00 AM - 5:00 PM',
    admissionFee: 630,
    avgVisitDuration: 180,
    nearestStation: 'Ueno Station (7 min walk)',
    features: ['English support', 'Interactive exhibits', 'Wheelchair accessible'],
  },
  {
    id: '22',
    name: 'Ameya Yokocho',
    category: 'Shopping District',
    type: 'attraction',
    rating: 4.0,
    reviewCount: 2787,
    ward: 'Ueno',
    address: '4 Chome Ueno, Taito',
    coordinates: { lat: 35.7100, lng: 139.7744 },
    images: ['https://www.japan-guide.com/g17/3012_01.jpg'],
    description: 'Bustling market street with over 400 shops selling everything from fresh fish to clothes. Experience old Tokyo atmosphere.',
    openingHours: '10:00 AM - 8:00 PM',
    admissionFee: 0,
    avgVisitDuration: 90,
    nearestStation: 'Ueno Station (1 min walk)',
    features: ['Street food', 'Shopping', 'Local atmosphere'],
  },
  {
    id: '23',
    name: 'Takeshita Street',
    category: 'Shopping District',
    type: 'attraction',
    rating: 4.0,
    reviewCount: 4525,
    ward: 'Harajuku',
    address: '1 Chome Jingumae, Shibuya',
    coordinates: { lat: 35.6706, lng: 139.7026 },
    images: ['https://www.planmyjapan.com/wp-content/uploads/2024/05/harajuku-17.jpg'],
    description: 'Iconic pedestrian street in Harajuku famous for youth fashion, kawaii culture, crepes, and trendy boutiques.',
    openingHours: '10:00 AM - 8:00 PM',
    admissionFee: 0,
    avgVisitDuration: 90,
    nearestStation: 'Harajuku Station (1 min walk)',
    features: ['Fashion shopping', 'Street food', 'Photo spots'],
  },
  {
    id: '24',
    name: 'Shibuya Sky',
    category: 'Observation Deck',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 284,
    ward: 'Shibuya',
    address: '2 Chome-24-12 Shibuya, Shibuya',
    coordinates: { lat: 35.6577, lng: 139.7034 },
    images: ['https://github.com/imnotkeril/images/blob/main/6437f1b2c6d3acf443a1e7493abceb45.jpg?raw=true'],
    description: 'Rooftop observatory on the 46th floor offering 360-degree views of Tokyo skyline. Interactive digital installations and open-air deck.',
    openingHours: '9:00 AM - 11:00 PM',
    admissionFee: 2200,
    avgVisitDuration: 90,
    nearestStation: 'Shibuya Station (5 min walk)',
    features: ['English support', 'Photography spot', 'Wheelchair accessible'],
  },
  {
    id: '25',
    name: 'Shinjuku Gyoen',
    category: 'Garden',
    type: 'attraction',
    rating: 4.6,
    reviewCount: 6357,
    ward: 'Shinjuku',
    address: '11 Naitocho, Shinjuku',
    coordinates: { lat: 35.6852, lng: 139.7100 },
    images: ['https://www.japan-guide.com/g18/3034_001_01.jpg'],
    description: 'Stunning garden combining Japanese traditional, English landscape, and French formal garden styles. Famous cherry blossom spot.',
    openingHours: '9:00 AM - 4:30 PM',
    admissionFee: 500,
    avgVisitDuration: 120,
    nearestStation: 'Shinjuku-gyoemmae Station (5 min walk)',
    features: ['Cherry blossoms', 'Picnic area', 'Photography spot'],
  },
  {
    id: '26',
    name: 'Tokyo Metropolitan Government Building',
    category: 'Observation Deck',
    type: 'attraction',
    rating: 4.4,
    reviewCount: 5586,
    ward: 'Shinjuku',
    address: '2 Chome-8-1 Nishishinjuku, Shinjuku',
    coordinates: { lat: 35.6896, lng: 139.6917 },
    images: ['https://www.japan-guide.com/g18/3011_21.jpg'],
    description: 'Twin towers with free observation decks on 45th floor offering panoramic Tokyo views. Best free viewpoint in the city.',
    openingHours: '9:30 AM - 10:00 PM',
    admissionFee: 0,
    avgVisitDuration: 60,
    nearestStation: 'Tochomae Station (1 min walk)',
    features: ['Free admission', 'Night views', 'Souvenir shop'],
  },
  {
    id: '27',
    name: 'Golden Gai',
    category: 'Nightlife District',
    type: 'attraction',
    rating: 4.0,
    reviewCount: 2307,
    ward: 'Shinjuku',
    address: '1 Chome-1 Kabukicho, Shinjuku',
    coordinates: { lat: 35.6938, lng: 139.7047 },
    images: ['https://res-4.cloudinary.com/dbm1qiew0/image/upload/q_auto/v1/blog-images/Shinjuku-Golden-Gai-Guide.jpg'],
    description: 'Network of narrow alleys with over 200 tiny bars and eateries. Unique Tokyo nightlife experience with intimate atmosphere.',
    openingHours: '6:00 PM - 5:00 AM',
    admissionFee: 0,
    avgVisitDuration: 120,
    nearestStation: 'Shinjuku Station (8 min walk)',
    features: ['Nightlife', 'Small bars', 'Local atmosphere'],
  },
  {
    id: '28',
    name: 'Samurai Museum',
    category: 'Museum',
    type: 'attraction',
    rating: 4.9,
    reviewCount: 1532,
    ward: 'Shinjuku',
    address: '2 Chome-25-6 Kabukicho, Shinjuku',
    coordinates: { lat: 35.6947, lng: 139.7022 },
    images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/62/e7/21/caption.jpg?w=1200&h=-1&s=1'],
    description: 'Interactive museum showcasing samurai history, armor, and weapons. Try on armor and watch sword demonstrations.',
    openingHours: '10:30 AM - 9:00 PM',
    admissionFee: 1900,
    avgVisitDuration: 90,
    nearestStation: 'Shinjuku Station (7 min walk)',
    features: ['English guide', 'Photo opportunities', 'Sword demonstrations'],
  },
  {
    id: '29',
    name: 'Gundam Unicorn Statue',
    category: 'Landmark',
    type: 'attraction',
    rating: 4.2,
    reviewCount: 221,
    ward: 'Odaiba',
    address: '1 Chome-1-10 Aomi, Koto',
    coordinates: { lat: 35.6246, lng: 139.7752 },
    images: ['https://img.cooljapan-videos.com/files/articles/u7v2gw2l/thumbnail/b63a0dee012f3de0b8185ad9dbe0479cba3200dd.jpg?202511261110'],
    description: 'Life-size Gundam Unicorn statue outside DiverCity Tokyo. Transforms with lighting effects at night.',
    openingHours: '24/7',
    admissionFee: 0,
    avgVisitDuration: 30,
    nearestStation: 'Tokyo Teleport Station (5 min walk)',
    features: ['Photo spot', 'Light show', 'Free admission'],
  },
  {
    id: '30',
    name: 'Odaiba Seaside Park',
    category: 'Park',
    type: 'attraction',
    rating: 4.3,
    reviewCount: 3000,
    ward: 'Odaiba',
    address: '1 Chome Daiba, Minato',
    coordinates: { lat: 35.6293, lng: 139.7744 },
    images: ['https://github.com/imnotkeril/images/blob/main/image%20(13).png?raw=true'],
    description: 'Beach park with views of Rainbow Bridge and Tokyo skyline. Popular spot for sunset and evening walks.',
    openingHours: '24/7',
    admissionFee: 0,
    avgVisitDuration: 90,
    nearestStation: 'Odaiba-kaihinkoen Station (3 min walk)',
    features: ['Beach', 'Rainbow Bridge views', 'Sunset spot'],
  },
];

const cafes: Place[] = [
  {
    id: 'c1',
    name: 'Blue Bottle Coffee Shinjuku',
    category: 'Cafe',
    type: 'cafe',
    rating: 4.0,
    reviewCount: 282,
    ward: 'Shinjuku',
    address: '3 Chome-4-8 Shinjuku, Shinjuku',
    coordinates: { lat: 35.6898, lng: 139.7024 },
    images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/e2/bb/5d/photo0jpg.jpg?w=900&h=500&s=1'],
    description: 'Minimalist cafe known for exceptional single-origin coffee and attention to brewing details.',
    openingHours: '8:00 AM - 9:30 PM',
    priceLevel: 2,
    avgVisitDuration: 45,
    cuisineTypes: ['Cafe', 'Coffee'],
    features: ['English menu', 'WiFi', 'Vegetarian options'],
  },
  {
    id: 'c2',
    name: 'Maid Cafe Maidreamin',
    category: 'Themed Cafe',
    type: 'cafe',
    rating: 3.6,
    reviewCount: 499,
    ward: 'Akihabara',
    address: '1 Chome-11-4 Sotokanda, Chiyoda',
    coordinates: { lat: 35.7020, lng: 139.7716 },
    images: ['https://github.com/imnotkeril/images/blob/main/MaidcafeexperienceinTokyoMaidreamin-KlookSingapore.jpg?raw=true'],
    description: 'Popular maid cafe chain offering quintessential Akihabara experience. Cute maids serve food and drinks with performances.',
    openingHours: '10:30 AM - 11:00 PM',
    priceLevel: 2,
    avgVisitDuration: 60,
    cuisineTypes: ['Cafe', 'Japanese'],
    features: ['Maid service', 'Photo opportunities', 'English menu'],
  },
  {
    id: 'r1',
    name: 'Sukiyabashi Jiro',
    category: 'Sushi',
    type: 'restaurant',
    rating: 4.0,
    reviewCount: 258,
    ward: 'Ginza',
    address: '4 Chome-2-15 Ginza, Chuo',
    coordinates: { lat: 35.6717, lng: 139.7632 },
    images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/d0/e6/36/caption.jpg?w=900&h=500&s=1'],
    description: "World-famous 3-Michelin-star sushi restaurant. Chef Jiro Ono's omakase is legendary. Advance booking required.",
    openingHours: '11:30 AM - 2:00 PM, 5:30 PM - 8:30 PM',
    priceLevel: 4,
    avgVisitDuration: 90,
    cuisineTypes: ['Sushi', 'Japanese'],
    features: ['English menu', 'Reservations required', 'Michelin 3-star'],
  },
  {
    id: 'r2',
    name: 'Ichiran Ramen',
    category: 'Ramen',
    type: 'restaurant',
    rating: 4.5,
    reviewCount: 2266,
    ward: 'Shibuya',
    address: '1 Chome-22-7 Jinnan, Shibuya',
    coordinates: { lat: 35.6627, lng: 139.7004 },
    images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/02/5d/1d/32/yummmm.jpg?w=900&h=500&s=1'],
    description: 'Famous tonkotsu ramen chain with individual booth seating. Customize your ramen to perfection. Open 24 hours.',
    openingHours: '24/7',
    priceLevel: 1,
    avgVisitDuration: 45,
    cuisineTypes: ['Ramen', 'Japanese'],
    features: ['English menu', 'Walk-in friendly', '24 hours', 'Vegetarian options'],
  },
  {
    id: 'r5',
    name: 'Gonpachi Nishiazabu',
    category: 'Izakaya',
    type: 'restaurant',
    rating: 3.8,
    reviewCount: 1822,
    ward: 'Minato',
    address: '1 Chome-13-11 Nishiazabu, Minato',
    coordinates: { lat: 35.6596, lng: 139.7253 },
    images: ['https://www.pickyeats.org/wp-content/uploads/2019/05/IMG_20171020_074727.jpg'],
    description: 'Traditional izakaya that inspired the fight scene in Kill Bill. Features live shamisen performances and yakitori.',
    openingHours: '11:30 AM - 3:30 AM',
    priceLevel: 2,
    avgVisitDuration: 120,
    cuisineTypes: ['Izakaya', 'Japanese', 'Yakitori'],
    features: ['English menu', 'Walk-in friendly', 'Open late'],
  },
];

const events: Event[] = [
  {
    id: 'e1',
    name: 'Cherry Blossom Festival',
    type: 'Festival',
    ward: 'Ueno',
    address: 'Ueno Park, Taito',
    coordinates: { lat: 35.7148, lng: 139.7744 },
    startDate: '2026-03-20',
    endDate: '2026-04-10',
    image: 'https://github.com/imnotkeril/images/blob/main/ueno-sakurafes01.jpg?raw=true',
    description: 'Annual cherry blossom festival featuring over 1,000 cherry trees in full bloom. Enjoy traditional performances, food stalls, and evening illuminations.',
    admissionFee: 0,
    tips: [
      'Best time: early morning to avoid crowds',
      'Bring picnic blanket for hanami',
      'Evening illuminations from 6-8 PM',
    ],
  },
  {
    id: 'e2',
    name: 'Sumida River Fireworks Festival',
    type: 'Fireworks',
    ward: 'Sumida',
    address: 'Sumida River, Sumida',
    coordinates: { lat: 35.7101, lng: 139.8107 },
    startDate: '2026-07-25',
    endDate: '2026-07-25',
    image: 'https://resources.matcha-jp.com/resize/720x2000/2019/06/06-78942.webp',
    description: "One of Tokyo's largest fireworks displays with over 20,000 fireworks lighting up the summer night sky.",
    admissionFee: 0,
    tips: [
      'Arrive 2-3 hours early for good viewing spots',
      'Wear yukata for authentic experience',
      'Expect large crowds',
    ],
  },
  {
    id: 'e3',
    name: 'Tokyo Game Show',
    type: 'Exhibition',
    ward: 'Chiba',
    address: 'Makuhari Messe, Chiba',
    coordinates: { lat: 35.6479, lng: 140.0344 },
    startDate: '2026-09-17',
    endDate: '2026-09-21',
    image: 'https://www.japan-guide.com/g18/6461_01.jpg',
    description: "Asia's largest gaming convention featuring upcoming game releases, esports tournaments, and industry panels.",
    admissionFee: 3000,
    website: 'https://tgs.cesa.or.jp/',
    tips: [
      'Book tickets in advance',
      'First two days are industry-only',
      'Wear comfortable shoes',
    ],
  },
  {
    id: 'e4',
    name: 'Shibuya Halloween',
    type: 'Cultural Event',
    ward: 'Shibuya',
    address: 'Shibuya Crossing, Shibuya',
    coordinates: { lat: 35.6595, lng: 139.7004 },
    startDate: '2026-10-31',
    endDate: '2026-10-31',
    image: 'https://www.datocms-assets.com/101439/1761970845-tokyo-shibuya-station-scramble-intersection.jpg?auto=format&h=1000&w=2000',
    description: 'Massive street party where thousands gather in costumes. The biggest Halloween celebration in Japan.',
    admissionFee: 0,
    tips: [
      'Arrive early - very crowded',
      'Be respectful of local businesses',
      'Use public transportation',
    ],
  },
];

const templateTours: TemplateTour[] = [
  {
    id: 'tokyo-classics-3d',
    title: 'Tokyo Classics 3 Days',
    days: 3,
    places: 12,
    estimatedCost: 18000,
    totalHours: 18,
    image: 'https://eijfa9g4ivj.exactdn.com/wp-content/uploads/2024/05/tokyo-155-1024x683.jpg?strip=all',
    description: 'Experience the iconic landmarks of Tokyo in 3 days including Senso-ji Temple, Tokyo Skytree, Meiji Shrine, and Shibuya Crossing.',
    highlights: [
      'Visit Senso-ji Temple in Asakusa',
      'Tokyo Skytree observation deck',
      'Meiji Shrine peaceful gardens',
      'Shibuya Crossing experience',
    ],
    placeIds: ['1', '2', 'r2', '5', '3', '4', 'c2', '6', '7', '8', 'r5'],
    isTemplate: true,
  },
  {
    id: 'otaku-2d',
    title: 'Otaku Paradise 2 Days',
    days: 2,
    places: 3,
    estimatedCost: 9000,
    totalHours: 12,
    image: 'https://www.trotop.be/wp-content/uploads/2025/02/Akihabara-Tokyo-Electric-Town-6.jpg',
    description: 'Dive into anime and manga culture in Akihabara.',
    highlights: [
      'Akihabara electric town',
      'Mandarake treasure hunting',
      'Maid cafe experience',
    ],
    placeIds: ['8', '15', 'c3', '14'],
    isTemplate: true,
  },
  {
    id: 'fuji-experience',
    title: 'Mt. Fuji Experience 2 Days',
    days: 2,
    places: 3,
    estimatedCost: 14000,
    totalHours: 14,
    image: 'https://www.japan-guide.com/g18/6933_01.jpg',
    description: 'Explore the beauty of Mt. Fuji with visits to the 5th Station, Lake Kawaguchiko, and scenic Oishi Park.',
    highlights: [
      'Mt. Fuji 5th Station views',
      'Lake Kawaguchiko boat tour',
      'Oishi Park flower fields',
    ],
    placeIds: ['18', '19', '20'],
    isTemplate: true,
  },
  {
    id: 'cultural-deep-dive',
    title: 'Cultural Deep Dive 3 Days',
    days: 3,
    places: 8,
    estimatedCost: 20000,
    totalHours: 20,
    image: 'https://delightfultravel.com.au/wp-content/uploads/2025/05/529de5da74b0d3df90c5da0b81eef92f.jpg',
    description: 'Immerse yourself in traditional Japanese culture with temples, museums, gardens, and performing arts.',
    highlights: [
      'Imperial Palace gardens',
      'Tokyo National Museum',
      'Kabukiza Theatre performance',
      'Traditional tea ceremony',
    ],
    placeIds: ['6', '9', '11', '12', '1', '3', '13'],
    isTemplate: true,
  },
];

let isSeeded = false;

export function seedDatabase() {
  // Prevent multiple seeding
  if (isSeeded) {
    return;
  }

  db.attractions.seed(attractions);
  db.cafes.seed(cafes);
  db.events.seed(events);
  db.templateTours.seed(templateTours);
  
  // Verify seeding
  const seededAttractions = db.attractions.getAll();
  if (seededAttractions.length === 0) {
    console.error('[Seed] ERROR: No attractions were seeded!');
  } else {
    console.log(`[Seed] Database initialized: ${seededAttractions.length} attractions, ${db.cafes.getAll().length} cafes, ${db.events.getAll().length} events, ${db.templateTours.getAll().length} tours`);
  }
  
  isSeeded = true;
}